# Generated by Django 5.2.6 on 2025-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='Generic Classroom', max_length=100),
        ),
    ]
