# Generated by Django 5.2.6 on 2025-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='hours_left',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='classroom',
            name='total_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
