# Generated by Django 5.2.6 on 2025-09-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroom_hours_left_classroom_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='booked_by',
        ),
    ]
