# Generated by Django 5.2.6 on 2025-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_classroom_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='total_hours',
            field=models.FloatField(default=8.0),
        ),
    ]
