# Generated by Django 5.2.6 on 2025-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_classroom_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='hours_left',
            field=models.FloatField(default=8.0, editable=False),
        ),
    ]
