# Generated by Django 5.2.6 on 2025-09-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_classroom_hours_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='hours_left',
            field=models.FloatField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='total_hours',
            field=models.FloatField(),
        ),
    ]
